### ISSUE TITLE
Original shipped configuration code style

### ISSUE THREAD

**Issue by goba** [irek02/acquia_connector#27]
Drupal does not export [] and {} for lists in YAML so even if the configuration will be kept the same, there will be a diff after importing / exporting the configuration. It is advised you use the same style as exported by Drupal so only meaningful diffs will be shown.

Ref: https://github.com/irek02/acquia_connector/blob/8.x-2.x/config/install/acquia_connector.settings.yml#L4 and similar lines

**Comment by varvashenya** [comment]
@goba thank you for your review
fixed
